OnlineShop/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChienVHShopOnline.Models;
using System.Net;
using System.Data.Entity;
using PagedList;

namespace ChienVHShopOnline.Controllers
{
    public class CategoryController : Controller
    {
        ChienVHShopDBEntities db = new ChienVHShopDBEntities();
        // GET: Category
        public ActionResult Index(int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 5;
            var catList = db.Categories.OrderBy(x => x.Name).ToPagedList(pageNumber, pageSize);
            return View(catList);
            //return View(db.Categories.OrderBy(x => x.Name).ToList());
        }

        public PartialViewResult CategoryPartial()
        {
            var categoryList = db.Categories.OrderBy(x => x.Name).ToList();
            return PartialView(categoryList);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Category/Edit/1
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryId,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Category/Details/1
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Delete/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                base.Dispose(disposing);
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShop/Controllers/ColorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChienVHShopOnline.Models;

namespace ChienVHShopOnline.Controllers
{
    public class ColorsController : Controller
    {
        private ChienVHShopDBEntities db = new ChienVHShopDBEntities();

        // GET: Colors
        public ActionResult Index()
        {
            return View(db.Colors.ToList());
        }

        // GET: Colors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Color color = db.Colors.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // GET: Colors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Colors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ColorId,Color1")] Color color)
        {
            if (ModelState.IsValid)
            {
                db.Colors.Add(color);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(color);
        }

        // GET: Colors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Color color = db.Colors.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // POST: Colors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ColorId,Color1")] Color color)
        {
            if (ModelState.IsValid)
            {
                db.Entry(color).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(color);
        }

        // GET: Colors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Color color = db.Colors.Find(id);
            if (color == null)
            {
                return HttpNotFound();
            }
            return View(color);
        }

        // POST: Colors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Color color = db.Colors.Find(id);
            db.Colors.Remove(color);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineShop/Views/Layout/_MainLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <link href="~/Content/style.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
</head>
<body>
    <div class="div-container">
        <div class="div-header">
            Shopping Online - Get Reward
        </div><!--div-header-->
        <div class="clear"></div>
        <div class="div-topmenu">
            <ul>
                <li>
                    @Html.ActionLink("Home", "Index", "Home") @**@
                </li>
                <li><a href="#">News</a></li>
                <li>
                    @Html.ActionLink("Products", "Index", "Products")
                </li>
                <li>
                    @Html.ActionLink("Contact Us", "Index", "ContactUs") @**@
                </li>
                <li>
                    @Html.ActionLink("Manage Color", "Index", "Colors") @**@
                </li>
                <li>
                    @Html.ActionLink("News Management", "Index", "NewsManagement") @**@
                </li>
                <li>
                    @Html.ActionLink("Cart", "Index", "ShoppingCart") @**@
                </li>
                <li>
                    @Html.ActionLink("Order", "Index", "Order") @**@
                </li>
            </ul>
        </div><!--div-topmenu-->
        <div class="clear"></div>
        <div class="div-left">
            <div class="category-title">Category</div><!--category-title-->
            <div class="category-list">
                @Html.Action("CategoryPartial", "Category")                
            </div><!--category-list-->
        </div><!--div-left-->
        <div class="div-main">
            <div class="top-breadcrumb">
                <ul>
                    <li><a href="#">Home</a><span class="span-breadcrumb">>></span></li>
                    <li><a href="#">Product</a></li>
                </ul>
            </div><!--top-breadcrumb-->
            <div class="clear"></div>
            <div class="main-content">
               @RenderBody()
            </div><!--main-content-->
        </div><!--div-main-->
        <div class="clear"></div>
        <div class="div-footer">
            <p>Copyright © @DateTime.Now.Year by Chien Vu Hoang. All rights reserved.</p>
            <p>Email: <a href="mailto:chien.vh@gmail.com">ChienVH</a></p>
            <p>Facebook: <a href="https://facebook.com/chienvh">https://facebook.com/chienvh</a> </p>
        </div><!--div-footer-->
    </div><!--div-container-->
</body>
</html>