OnlineShop/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChienVHShopOnline.Models;
using PagedList;
using System.Net;

namespace ChienVHShopOnline.Controllers
{
    public class ProductsController : Controller
    {
        ChienVHShopDBEntities db = new ChienVHShopDBEntities();
        // GET: Products
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult ProductListPartial(int? page, int? category)
        {
            var pageNumber = page ?? 1;
            var pageSize = 10;
            if (category != null)
            {
                ViewBag.category = category;
                var productList = db.Products
                                .OrderByDescending(x => x.ProductId)
                                .Where(x=> x.CategoryId == category)
                                .ToPagedList(pageNumber, pageSize);
                return PartialView(productList);
            }
            else
            {
                var productList = db.Products.OrderByDescending(x => x.ProductId).ToPagedList(pageNumber, pageSize);
                return PartialView(productList);
            }
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
    }
}

OnlineShop/Controllers/ShoppingCartController.cs
using ChienVHShopOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PayPal.Api;

namespace ChienVHShopOnline.Controllers
{
    public class ShoppingCartController : Controller
    {
        ChienVHShopDBEntities db = new ChienVHShopDBEntities();
        private string strCart = "Cart";
        // GET: ShoppingCart
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OrderNow(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            if (Session[strCart] == null)
            {
                List<Cart> lsCart = new List<Cart>
                {
                    new Cart(db.Products.Find(id),1)
                };
                Session[strCart] = lsCart;
            }
            else
            {
                List<Cart> lsCart = (List<Cart>)Session[strCart];
                int check = IsExistingCheck(id);
                if (check == -1)
                    lsCart.Add(new Cart(db.Products.Find(id), 1));
                else
                    lsCart[check].Quantity++;
                Session[strCart] = lsCart;
            }
            return View("Index");
        }

        private int IsExistingCheck(int? id)
        {
            List<Cart> lsCart = (List<Cart>)Session[strCart];
            for (int i = 0; i < lsCart.Count; i++)
            {
                if (lsCart[i].Product.ProductId == id) return i;
            }
            return -1;
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            int check = IsExistingCheck(id);
            List<Cart> lsCart = (List<Cart>)Session[strCart];
            lsCart.RemoveAt(check);
            return View("Index");
        }

        public ActionResult UpdateCart(FormCollection frc)
        {
            string[] quantities = frc.GetValues("quantity");
            List<Cart> lstCart = (List<Cart>)Session[strCart];
            for (int i = 0; i < lstCart.Count; i++)
            {
                lstCart[i].Quantity = Convert.ToInt32(quantities[i]);
            }
            Session[strCart] = lstCart;
            return View("Index");
        }

        public ActionResult CheckOut()
        {
            return View("CheckOut");
        }

        public ActionResult ProcessOrder(FormCollection frc)
        {
            List<Cart> lstCart = (List<Cart>)Session[strCart];
            //1. Save the order into Order table
            var order = new ChienVHShopOnline.Models.Order()
            {
                CustomerName = frc["cusName"],
                CustomerPhone = frc["cusPhone"],
                CustomerEmail = frc["cusEmail"],
                CustomerAddress = frc["cusAddress"],
                OrderDate = DateTime.Now,
                PaymentType = "Cash",
                Status = "Processing"
            };
            db.Orders.Add(order);
            db.SaveChanges();

            //2. Save the order detail into Order Detail table
            foreach (Cart cart in lstCart)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    OrderID = order.OrderID,
                    ProductID = cart.Product.ProductId,
                    Quantity = cart.Quantity,
                    Price = cart.Product.Price
                };
                db.OrderDetails.Add(orderDetail);
                db.SaveChanges();
            }
            //3. Remove shopping cart session
            Session.Remove(strCart);
            return View("OrderSuccess");
        }

        // Work with Paypal Payment
        private Payment payment;

        // Create a paypment using an APIContext
        private Payment CreatePayment(APIContext apiContext, string redirectUrl)
        {
            var listItems = new ItemList() { items = new List<Item>() };

            List<Cart> listCarts = (List<Cart>)Session[strCart];
            foreach (var cart in listCarts)
            {
                listItems.items.Add(new Item()
                {
                    name = cart.Product.ProductName,
                    currency = "USD",
                    price = cart.Product.Price.ToString(),
                    quantity = cart.Quantity.ToString(),
                    sku = "sku"
                });
            }

            var payer = new Payer() { payment_method = "paypal" };

            // Do the configuration RedirectURLs here with redirectURLs object
            var redirUrls = new RedirectUrls()
            {
                cancel_url = redirectUrl,
                return_url = redirectUrl
            };

            // Create details object
            var details = new Details()
            {
                tax = "1",
                shipping = "2",
                subtotal = listCarts.Sum(x => x.Quantity * x.Product.Price).ToString()
            };

            // Create amount object
            var amount = new Amount()
            {
                currency = "USD",
                total = (Convert.ToDouble(details.tax) + Convert.ToDouble(details.shipping) + Convert.ToDouble(details.subtotal)).ToString(),// tax + shipping + subtotal
                details = details
            };

            // Create transaction
            var transactionList = new List<Transaction>();
            transactionList.Add(new Transaction()
            {
                description = "Chien Testing transaction description",
                invoice_number = Convert.ToString((new Random()).Next(100000)),
                amount = amount,
                item_list = listItems
            });

            payment = new Payment()
            {
                intent = "sale",
                payer = payer,
                transactions = transactionList,
                redirect_urls = redirUrls
            };

            return payment.Create(apiContext);
        }

        // Create ExecutePayment method
        private Payment ExecutePayment(APIContext apiContext, string payerId, string paymentId)
        {
            var paymentExecution = new PaymentExecution()
            {
                payer_id = payerId
            };
            payment = new Payment() { id = paymentId };
            return payment.Execute(apiContext, paymentExecution);
        }

        // Create PaymentWithPaypal method
        public ActionResult PaymentWithPaypal()
        {
            // Gettings context from the paypal bases on clientId and clientSecret for payment
            APIContext apiContext = PaypalConfiguration.GetAPIContext();

            try
            {
                string payerId = Request.Params["PayerID"];
                if (string.IsNullOrEmpty(payerId))
                {
                    // Creating a payment
                    string baseURI = Request.Url.Scheme + "://" + Request.Url.Authority + "/ShoppingCart/PaymentWithPaypal?";
                    var guid = Convert.ToString((new Random()).Next(100000));
                    var createdPayment = CreatePayment(apiContext, baseURI + "guid=" + guid);

                    // Get links returned from paypal response to create call funciton
                    var links = createdPayment.links.GetEnumerator();
                    string paypalRedirectUrl = string.Empty;

                    while (links.MoveNext())
                    {
                        Links link = links.Current;
                        if (link.rel.ToLower().Trim().Equals("approval_url"))
                        {
                            paypalRedirectUrl = link.href;
                        }
                    }

                    Session.Add(guid, createdPayment.id);
                    return Redirect(paypalRedirectUrl);
                }
                else
                {
                    // This one will be executed when we have received all the payment params from previous call
                    var guid = Request.Params["guid"];
                    var executedPayment = ExecutePayment(apiContext, payerId, Session[guid] as string);
                    if (executedPayment.state.ToLower() != "approved")
                    {
                        //Remove shopping cart session
                        Session.Remove(strCart);
                        return View("Failure");                        
                    }
                }
            }
            catch (Exception ex)
            {
                PaypalLogger.Log("Error: "+ ex.Message);
                //Remove shopping cart session
                Session.Remove(strCart);
                return View("Failure");
            }

            //Remove shopping cart session
            Session.Remove(strCart);
            return View("Success");
        }
    }
}

OnlineShop/Views/ShoppingCart/CheckOut.cshtml
@using ChienVHShopOnline.Models;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_MainLayout.cshtml";
}

<h2>Check Out Shopping Cart</h2>

@{
    if (Session["Cart"] != null)
    {
        <table class="shopping-cart">
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Sub Total</th>
            </tr>

            @foreach (var cart in (List<Cart>)Session["Cart"])
                {
                <tr>
                    <td>@Html.ActionLink(cart.Product.ProductName, "Details", "Products", new { id = cart.Product.ProductId }, new { @class = "delete-shopping" })</td>
                    <td>$@(String.Format("{0:N0}", cart.Product.Price))</td>
                    <td>
                        <input type="text" name="quantity" id="quantity" value="@cart.Quantity" readonly />
                    </td>
                    <td>$@(String.Format("{0:N0}", cart.Product.Price * cart.Quantity))</td>
                </tr>
            }@*End of foreach cart items*@

            <tr>
                <td colspan="3" class="total-price-text">Total:</td>
                <td class="total-price-digit">
                    @{
                        List<Cart> temp = (List<Cart>)Session["Cart"];
                        var total = String.Format("{0:N0}", temp.Sum(x => x.Quantity * x.Product.Price));
                    }

                    $@total
                </td>
            </tr>
        </table>
                        } @*End of if session*@
else
{
    <h4> No items in your cart!!!</h4>
}
}

<br />
@using (Html.BeginForm("ProcessOrder", "ShoppingCart", FormMethod.Post, new { id = "customer-form" }))
{

    <table>
        <tr>
            <td colspan="3" style="text-align:center;"><b>Customer's Information</b></td>
        </tr>
        <tr>
            <td>Customer Name:</td>
            <td><input type="text" name="cusName" /></td>
        </tr>
        <tr>
            <td>Customer Phone:</td>
            <td><input type="text" name="cusPhone" /></td>
        </tr>
        <tr>
            <td>Customer Email:</td>
            <td><input type="text" name="cusEmail" /></td>
        </tr>
        <tr>
            <td>Customer Address:</td>
            <td><input type="text" name="cusAddress" /></td>
        </tr>
        <tr>
            <td colspan="3"><input type="submit" value="Process Order" class="update-shopping"/></td>
        </tr>
    </table>
}

<script type="text/javascript">
    $("#customer-form").validate({
        rules: {
            cusName: {
                required: true
            },
            cusPhone: {
                required: true
            },
            cusEmail: {
                required: true
            },
            cusAddress: {
                required: true
            }
        }
    });
</script>

OnlineShop/Views/ShoppingCart/Failure.cshtml
@{
    ViewBag.Title = "Failure";
    Layout = "~/Views/Layout/_MainLayout.cshtml";
}

<h2>Failure</h2>

OnlineShop/Views/ShoppingCart/Index.cshtml
@using ChienVHShopOnline.Models;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_MainLayout.cshtml";
}

<h2>Index</h2>

@{
    if (Session["Cart"] != null)
    {

        using (Html.BeginForm("UpdateCart", "ShoppingCart", FormMethod.Post))
        {
            <table class="shopping-cart">
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Sub Total</th>
                </tr>

                @foreach (var cart in (List<Cart>)Session["Cart"])
                {
                    <tr>
                        <td>@Html.ActionLink(cart.Product.ProductName, "Details", "Products", new { id = cart.Product.ProductId }, new { @class = "delete-shopping" })</td>
                        <td>$@(String.Format("{0:N0}", cart.Product.Price))</td>
                        <td>
                            <input type="text" name="quantity" id="quantity" value="@cart.Quantity" />
                            &nbsp;<span id="errmsg"></span>
                        </td>
                        <td>$@(String.Format("{0:N0}", cart.Product.Price * cart.Quantity))</td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", "ShoppingCart", new { id = cart.Product.ProductId },
                            new { onclick = "return confirm ('Are you sure you want to delete this?');", @class ="delete-shopping" })
                        </td>
                    </tr>
                }@*End of foreach cart items*@

                <tr>
                    <td colspan="3" class="total-price-text">Total:</td>
                    <td class="total-price-digit">
                        @{
                            List<Cart> temp = (List<Cart>)Session["Cart"];
                            var total = String.Format("{0:N0}", temp.Sum(x => x.Quantity * x.Product.Price));
                        }

                        $@total
                    </td>
                </tr>
            </table>
            <br />
            @Html.ActionLink("Continue Shopping", "Index", "Products",null, new { @class = "continue-shopping"})
            <input type="submit" value="Update Cart" class="update-shopping" />
            @Html.ActionLink("CheckOut", "CheckOut", "ShoppingCart",null, new { @class = "continue-shopping"})
            @Html.ActionLink("CheckOut With Paypal", "PaymentWithPaypal", "ShoppingCart",null, new { @class = "continue-shopping"})
        } @*End of form*@

    } @*End of if session*@

    else
    {
        <h4> No items in your cart!!!</h4>
    }

}

    <script type="text/javascript">
        $(document).ready(function () {
            //called when key is pressed in textbox
            $("#quantity").keypress(function (e) {
                //if the letter is not a digit, we will display the error message and dont allow them to type anything
                if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                    //we will display error message
                    $("#errmsg").html("Enter digits only!").show().fadeOut("slow");
                    return false;
                }
            });
        });
    </script>

OnlineShop/Views/ShoppingCart/OrderSuccess.cshtml
@{
    ViewBag.Title = "OrderSuccess";
    Layout = "~/Views/Layout/_MainLayout.cshtml";
}

<h4>Your order has been placed successfully. Please click @Html.ActionLink("Here","Index","Home") to go to home page!!!</h4>

OnlineShop/Views/ShoppingCart/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Layout/_MainLayout.cshtml";
}

<h2>Success</h2>